### ISSUE TITLE
Wrong CSS specificity

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/jss#1045]
Take the following style as an input:
```js
const style = {
  root: {
    "&:hover": {
      "& $icon": {
        color: "red"
      }
    },
    "&.active": {
      "& $icon": {
        color: "blue"
      }
    }
  },
  icon: {},
};
```

__Expected behavior:__
I would expect the following CSS injected into the page:
```css
.root-0-0-1:hover .icon-0-0-2 {
  color: red;
}
.root-0-0-1.active .icon-0-0-2 {
  color: blue;
}
```

__Describe the bug:__
The following CSS is injected in the page:
```css
.root-0-0-1.active .icon-0-0-2 {
  color: blue;
}
.root-0-0-1:hover .icon-0-0-2 {
  color: red;
}
```

__Codesandbox link:__ 
Please create a codesandbox.io with the issue. Make it as minimal as possible as this will help us find the bug quicker.

https://codesandbox.io/s/yjyqmo4vqv

__Versions (please complete the following information):__
 - jss: 10.0.0-alpha.11
