### ISSUE TITLE
[jss-default-unit] Default units missing when expanding and extending

### ISSUE THREAD

**Issue by joakimbugge** [cssinjs/jss#1070]
When using extend combined with expand, the default units are missing from the property in the extending object. (Note that I also use @global, in case that matters.)

```javascript
import jss from 'jss';
import preset from 'jss-preset-default';
import defaultUnit from 'jss-default-unit';

jss.use(defaultUnit({ 'margin': 'em', 'font-size': 'em' }));
jss.setup(preset());

const h1 = {
    fontSize: 2,
    margin: [0, 0, 1, 0],
};

const h2 = {
    extend: h1,
    fontSize: 1.5,
};

jss.createStyleSheet({
  '@global': {
        h1,
        h2,
  }
}).attach();
```

The `fontSize` property has the em unit as expected, while `margin` is missing the em unit. Output:

```css
h1 {
  margin: 0 0 1em 0;
  font-size: 2em;
}
h2 {
  margin: 0 0 1 0;
  font-size: 1.5em;
}
```
