### ISSUE TITLE
Dynamic selectors

### ISSUE THREAD

**Issue by turnerhayes** [cssinjs/jss#1088]
__Is your feature request related to a problem? Please describe.__

I'm trying to generate an `nth-child(x)` selector where the `x` is derived from a prop value. 

__Describe the solution you'd like__
something along these lines:

```js
withStyles({
  root: (props) => ({
    color: "red",

    [`&:nth-child(${props.someNum}n)`]: {
      color: "blue",
    },
  })
});
```

which would generate:

```css
.ClassFoo-root {
  color: red;
}

.ClassFoo-root:nth-child(4n) {
  color: blue;
}
```
if the component was pass the props `{ someNum: 4}`

__Are you willing to implement it?__
Potentially; depends how complex the solution would be (I don't know what the implications of making style objects accept functions as well as objects would be).
