### ISSUE TITLE
Multiple @font-face doesn't work with typescript

### ISSUE THREAD

**Issue by CutmastaD** [cssinjs/jss#1097]
__Expected behavior:__
I expect that 
``` javascript
const styles = {
  '@font-face': [
    {
      fontFamily: 'MyWebFont',
      src: 'url(webfont.eot)'
    },
    {
      fontFamily: 'MySecondFont',
      src: 'url(webfont2.eot)'
    }
  ]
}
```
gets compiled to
``` css
@font-face {
  font-family: 'MyWebFont';
  src: url('webfont.eot');
}
@font-face {
  font-family: 'MySecondFont';
  src: url('webfont2.eot');
}
```
like it is described in the cssinjs documentation: https://cssinjs.org/jss-syntax/?v=v10.0.0-alpha.16#font-face

__Describe the bug:__
Typescript compile error:
```
Types of property '"@font-face"' are incompatible.
Type '{ fontFamily: string; src: string; }[]' is not assignable to type 'CSSProperties<{}>'.
Index signature is missing in type '{ fontFamily: string; src: string; }[]'.  TS2345
```

__Versions:__
 - react-jss: 8.6.1
 - typescript: 3.4.5
