### ISSUE TITLE
Nested selectors are loosing dollar sign

### ISSUE THREAD

**Issue by Nesvet** [cssinjs/jss#1116]
__Expected behavior:__
Normal selector nesting

__Describe the bug:__
When nesting a selector with a dollar sign, it disappears

__Codesandbox link:__ 
[https://codesandbox.io/s/react-jss-playground-j9toj](https://codesandbox.io/s/react-jss-playground-j9toj)

There I've just added:
```javascript
    "& h1": {
      color: "red"
    }
```
And changed `Comp` to `Comp$1`

And look at the `<style>`:
```css
.Comp\$1-wrapper-0-1-13 {
  padding: 40px;
  background: #f7df1e;
  text-align: left;
}
.Comp\1-wrapper-0-1-13 h1 {
  color: red;
}
```

__Versions:__
 - react-jss: 8.6.1
 - Browser: Safari 12.1.2
 - OS: macOS 10.14.6
