### ISSUE TITLE
Nesting after using multiple refs in selector doesn't work

### ISSUE THREAD

**Issue by jwarkentin** [cssinjs/jss#1185]
__Expected behavior:__

For nesting under a selector with more than a single ref, the only way to make it useful is to make sub-refs behave as the parent refs, like so:
```js
{
  grouped: {
    'button&, &:not(button) button': {
      borderRight: '1px solid #000',

      '&$disabled': {
        borderRight: '1px solid #AAA'
      }
    }
  },
  disabled: {}
}
```

Should produce:
```css
button.grouped, .grouped:not(button) button {
  border-right: 1px solid #000
}

button.grouped.disabled, .grouped.disabled:not(button) button {
  border-right: 1px solid #000
}
```

__Describe the bug:__
Instead of the above, the actual output ends up like looking this:
```css

button.grouped, .grouped:not(button) button {
  border-right: 1px solid #000
}

button.grouped, .grouped:not(button) button.disabled {
  border-right: 1px solid #000
}
```

Nothing about that selector is correct based on how I would expect refs to work or even useful. I can't think of any way to make a nested selector useful the way that currently works if a parent selector above it uses more than one ref.

It's also worth noting that even without any refs, it doesn't currently treat comma separated lists any different from other selectors so it just appends to the end of the string instead of the end of each comma separated selector, which is also always the wrong behavior with nesting.

The simplest solution might be resolving the most deeply nested refs first and then working up the tree. Sub-selectors need to be appended to each parent ref rather than just the end of the selector. If no refs are used, nested selectors should be appended to each of the parent selector list items.
