### ISSUE TITLE
@font-face compiled with incorrect font src order

### ISSUE THREAD

**Issue by 3axap4eHko** [cssinjs/jss#1217]
__Expected behavior:__
According to the documentation provided here https://cssinjs.org/jss-syntax/?v=v10.0.0#font-face the following js code
```js
const styles = {
  '@font-face': {
    fontFamily: 'MyWebFont',
    src: 'url(webfont.eot)',
    fallbacks: [
      {src: 'url(webfont.eot?#iefix) format(embedded-opentype)'},
      {src: 'url(webfont.woff2) format(woff2)'}
    ]
  }
}
```

Should be compiled to the following css code

```css
@font-face {
  font-family: MyWebFont;
  src: url('webfont.eot');
  src: url(webfont.eot?#iefix) format(embedded-opentype);
  src: url(webfont.woff2) format(woff2);
}
```

__Describe the bug:__
But it compiles to the
```css
@font-face {
  src: url(webfont.eot?#iefix) format(embedded-opentype);
  src: url(webfont.woff2) format(woff2);
  font-family: 'MyWebFont';
  src: url(webfont.eot);
}
```

As you can notice, the order of the provided sources is incorrect
__Codesandbox link:__ 
https://codesandbox.io/s/6n0k5npqpk

__Versions (please complete the following information):__
 - jss: v10.0.0
 - Browser Chrome 77
 - macOS:

It would be great to have or well-explained behavior in the documentation or fix this issue.
Also attached doc screenshot to avoid confusion with examples:

<img width="577" alt="Screen Shot 2019-10-15 at 7 53 13 PM" src="https://user-images.githubusercontent.com/1630657/66877909-7ee2ea80-ef85-11e9-8ea3-17bb9cd580f1.png">

**Comment by 3axap4eHko** [comment]
ping

**Comment by kof** [comment]
documentation is wrong, fallback for any property is always rendered first in CSS, then the property that might work or not.

**Comment by 3axap4eHko** [comment]
@kof looks like you are wrong. The browser will try to use the font you specified first, but if it doesn’t have that font available, it will keep going down that list.

**Comment by 3axap4eHko** [comment]
ping

**Comment by kof** [comment]
The confusion here comes from 2 different syntaxes CSS offers which [work differently ](https://codesandbox.io/s/zealous-hawking-r5dz3):

```css
@font-face {
  font-family: font1;
  src: local("Arial"), local("Verdana");
}
@font-face {
  font-family: font2;
  src: local("Arial");
  src: local("Verdana");
}
```

When you use fallbacks, you are using the second syntax, to use the first one you just need to define the src in one property.

We may need to remove that example with fallbacks for font-face though, because most men https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face hows how to use the first syntax only and that's what people are probably using.
