### ISSUE TITLE
Atomic generator 

### ISSUE THREAD

**Issue by behnammodi** [cssinjs/jss#1462]
We generate a lot of common style somethings like this:

```css
.a1-0-1-105 {
  display: none;
}

.a2-0-1-106 {
  display: none;
}
```

And style sheet size is increasing in a large project

We can use an atomic style generator, Some of the libraries did it like: 

https://github.com/robinweser/fela

And

https://github.com/styletron/styletron

Are you willing to implement it? Yes
