### ISSUE TITLE
[jss-nested] target a rule from the same sheet when possible

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#214]
Sometimes we need to create a nested selector targeted to a child class from the same sheet, for e.g. when we want to change a style for some inner element.

In this case, button is a global selector scoped to the container selector
```javascript
{
  container:  {
    '&:hover button': {
      color: 'red'
    }
  }
}
```

Results in something like this:

```css
.container-jss-0-0:hover button {
  color: red;
}
```

Now we want to target an element with generated class name:

```javascript
{
 button: {
   color: 'blue' 
 },
  container:  {
    '&:hover button': {
      color: 'red'
    }
  }
}
```

Now we checked that button is defined on the same sheet, so lets use the generated for it selector.

```css
.container-jss-0-1:hover .button-jss-0-0 {
  color: red;
}
```
