### ISSUE TITLE
Extend across stylesheets —

### ISSUE THREAD

**Issue by tusharmath** [cssinjs/jss#283]
```js
const jss = require('jss').default
const preset = require('jss-preset-default').default
jss.setup(preset())

// Style 1
jss.createStyleSheet({
  'flexRow': { display: 'flex'}
})

// Style 2
jss.createStyleSheet({
  button: {
    fontSize: 12,
    extend: 'flexRow'
  }
})

console.log(jss.sheets.toString())
```

Current
```css
flexRow {
  display: flex;
}
.button-2242923773 {
  font-size: 12px;
}
```

Expected

```css
flexRow {
  display: flex;
}
.button-2242923773 {
  font-size: 12px;
  display: flex;
}
```

How can I solve this problem? Is there a way around it?
