### ISSUE TITLE
Media query not working as expect from example

### ISSUE THREAD

**Issue by techniq** [cssinjs/jss#284]
I'm attempting to setup a [Codepen](http://codepen.io/techniq/pen/PzXzRL?editors=0010) to get a feel for JSS and I'm having trouble running the [example](https://github.com/cssinjs/jss#example) in the README.  Currently the media query doesn't appear to get applied until the button is hovered, although when I paste the following from the example into the [repl](https://cssinjs.github.io/repl/) it appears to create the correct CSS classes.

```js
return {
  button: {
    fontSize: 12,
    '&:hover': {
      background: 'blue'
    }
  },
  ctaButton: {
    extend: 'button',
    '&:hover': {
      background: 'red'
    }
  },
  '@media (min-width: 1024px)': {
    button: {
      minWidth: 200
    }
  }
}
```

creates
```css
.button-1289375814 {
  font-size: 12px;
}
.ctaButton-2123192516 {
  font-size: 12px;
}
@media (min-width: 1024px) {
  .button-1289375814 {
    min-width: 200px;
  }
}
.button-1289375814:hover {
  background: blue;
}
.ctaButton-2123192516:hover {
  background: red;
}
```

---
Semi related, is it possible (maybe through one of the plugins) to nest media queries?
For example:
```js
return {
  button: {
    fontSize: 12,
    '&:hover': {
      background: 'blue'
    },
    '@media (min-width: 1024px)': {
      minWidth: 200
    }
  },
  ctaButton: {
    extend: 'button',
    '&:hover': {
      background: 'red'
    }
  }
}
```
