### ISSUE TITLE
[jss-nested] Nested comma separated style declarations

### ISSUE THREAD

**Issue by alurim** [cssinjs/jss#299]
Consider the following style declaration:

```
const styles = {
  someDiv: {
    '&:hover, &:focus, &:active': {
      '& $someNestedDiv': {
        color: 'red',
      }
    }
  }
}
```

I thought that the styles rendered would look like this:

```
.someDiv:hover .someNestedDiv, .someDiv:focus .someNestedDiv, .someDiv:active .someNestedDiv {
  color: red
}
```

but actually it looks like this: 

```
.someDiv:hover, .someDiv:focus, .someDiv:active .someNestedDiv {
  color: red
}
```

What do you think about switching the behavior to what I expected it to be? Or is it bad form to be specifyiny rules with commas (and if so is that documented somewhere?)

**Comment by kof** [comment]
What you did won't work at all ... the object inside of a nested rule is not a new rule, it is props.

```
const styles = {
  someDiv: {
    '&:hover, &:focus, &:active': {
        color: 'red',
    }
  }
}

```

**Comment by alurim** [comment]
Ah whoops @kof! I edited my original question as I forgot the key `& $` prefixing the `someNestedDev` which makes it a rule not props, right?

**Comment by kof** [comment]
this is still not correct, I assume $someNestedDiv rule need to be defined ....

**Comment by kof** [comment]
you mean something like this

```
 {
  someDiv: {
    '&:hover, &:focus, &:active': {
      '& $someNestedDiv': {
        color: 'red',
      }
    }
  },
  someNestedDiv: {
    float: 'left'
  }
}
```

```css
.someNestedDiv-3787690649 {
  float: left;
}
.someDiv-4073602825:hover, .someDiv-4073602825:focus, .someDiv-4073602825:active .someNestedDiv-3787690649 {
  color: red;
}
```
