### ISSUE TITLE
Global styles do not fall into `sheets.toString()` method

### ISSUE THREAD

**Issue by grigory-leonenko** [cssinjs/jss#340]
**As now:**
Global styles don't inlining if `sheets.toString()` method called, it's important to criticalCss styles. It's bug or some option must be specified?

**Comment by kof** [comment]
What do you mean by global styles? What do you expect .... please describe the full situation.

**Comment by grigory-leonenko** [comment]
Yes i have app container with global styles:
```css
export default {
  body: {
    margin: 0,
    padding: 0,
    color: '#333333',
  },

  '*:after, *:before, *': {
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    color: 'inherit',
  },
};
```
And react-jss connector:
```javascript
export default useSheet(styles, { named: false })(App);
```
In server render middleware i'am trying to get my styles:
```javascript
const render = {
   html,
   css: jss.sheets.toString(),
}
```
I expected global styles inlined to string, otherwise all this makes no sense get styles from modules, layout will broken.
