### ISSUE TITLE
[jss-expand] Make border-radius part of border object

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#344]
Allow syntax like that `border: {radius: 1}`.

**Comment by kof** [comment]
cc @typical000

**Comment by typical000** [comment]
Solved, created PR, you can review it here:

- Added back forgotten npm command for 'benchmark'
- Added possibility to create custom properties (included border-radius)

For e.g., if we add in props.js scheme like this

``````````````js
export const expandedPropObj = {
  border: {
    radius: 'border-radius'
  },
  size: { // Here you need to look
    x: 'width',
    y: 'height'
  }
}
``````````````
In JSS we can write this:

``````````````js
var sheet = jss.createStyleSheet({
    a: {
      size: {
        x: 100,
        y: 500
      }
    }
});

``````````````
Result will be:

``````````````css
.a-2678628283 {

  width: 200;

  height: 500;

}

``````````````

But this feature need more sophisticated approach about integration with *jss-default-unit* because as much we create such "custom" properties - we need to add them more and more in defaultUnit.js config.
For example, for above new 'size' property we need to add to *jss-default-unit* something like this:
``````````````js
  size-x: 'px',
  size-y: 'px',

``````````````
And, I personally, dislike this, because we need to add "the same" things in different repos. But, I don't know how to solve this. Because - in one hand this things are 'properties' in terms of any jss plugin, and, in other hand, this is stuff only of jss-expand... TBD.

Anyway, with border-radius it was all ok thanks to my precedent PR - https://github.com/cssinjs/jss-default-unit/pull/9

**Comment by typical000** [comment]
Maybe make 'expandedPropObj' (renamed to customPropObj) public as option for plugin so users can create their own new rules? And document it

**Comment by kof** [comment]
Hmm, we can do that, even if probability someone will use it is not high. I think for public api a better name is "customProps".

**Comment by typical000** [comment]
Just realized, that we can solve with this piece of code:
`````````````js
export const customPropObj = {
  border: {
    radius: 'border-radius'
  },
  background: {
    size: 'background-size'
  },
  font: {
    style: 'font-style',
    variant: 'font-variant',
    weight: 'font-weight',
    size: 'font-size',
    family: 'font-family',
    lineHeight: 'line-height', // Needed to avoid compilation issues with jss-camel-case
    'line-height': 'line-height'
  }
}
`````````````
- Font property issue described in readme.md (due to existanse of symbol `/` inside stynax that separates `font-size` and `line-height`)
Original text from readme:
>
This plugin doesn't support font property written in expanded way. This is because plugin must have maximum performance, and all exceptions like in font way of writing (joining of font-size and line-height joining with \ symbol) is forbidden.

- Background-size property. Inside `background` shorthand we must use `/` to write size.

So, this code:
`````````````js
var sheet = jss.createStyleSheet({
  a: {
    border: {
      radius: ['5px', '10px']
    },
    font: {
      style: 'italic',
      variant: 'small-caps',
      weight: 'bold',
      size: 15,
      lineHeight: 5,
      family: 'Arial, Sans-serif'
    }
  },
  b: {
    background: {
      repeat: 'no-repeat',
      size: 'cover',
      image: 'some/url'
    }
  }
});
`````````````
Will be compiled to:
`````````````css
.a-3073098024 {
  border-radius: 5px 10px;
  font-style: italic;
  font-variant: small-caps;
  font-weight: bold;
  font-size: 15px;
  font-family: Arial, Sans-serif;
  line-height: 5; /* <-- Here is a problem. Need to add 'font-line-height' to jss-default unit as 'non-existant' property. Need to make after a PR. */
}
.b-3744651135 {
  background: some/url no-repeat;
  background-size: cover;
}
`````````````

@kof what do you think? As for me - we can add this piece of code inside config. As for `font` property - yes, it is bad to write it not as shorthand, but I don't see any other quick solution without performance impacts
