### ISSUE TITLE
[jss-expand] Support for transform property

### ISSUE THREAD

**Issue by typical000** [cssinjs/jss#365]
Recently, I wrote a little piece of styles where I have used a lot of `transform` properties.
So I have faced the problem, that we don't have any good solution to write this prop.

Now in JSS we write:
````````````````````````````js
var sheet = jss.createStyleSheet({
  a: {
    transform: 'translate(10px, 20px) rotate(50deg)'
  }
});
````````````````````````````
What if we extend functionality of jss-expand to write in this manner:
````````````````````````````js
var sheet = jss.createStyleSheet({
  a: { // A little better, but this approach doesn't support jss-default units, etc.
    transform: [
      'translate(10px, 20px)',
      'rotate(50deg)'
    ]
  },
  b: {
    transform: { // The best one solution as I think
      translateX: 10, // Use numbers
      scale: [2, 0.5], // Or array
      matrix: [2, 0, 0, 1, 0, 0]
    }
  }
})
````````````````````````````
And the output
````````````````````````````css
a {
  transform: translate(10px, 20px) rotate(50deg);
}
b {
  transform: translateX(10px) scale(2, 0.5) matrix(2, 0, 0, 1, 0, 0);
}
````````````````````````````

@kof wdut?
