### ISSUE TITLE
[jss-nested] after updating up to jss 6.0.0 plugin is totally broken

### ISSUE THREAD

**Issue by typical000** [cssinjs/jss#382]
Prerequisites: using last jss + jss-preset-default
This code:
`````````````````````````````````````js
var sheet = jss.createStyleSheet({
  test: {
    background: 'red'
  },
  block: {
    color: 'red',
    padding: 10,
    border: {
      width: 2,
      style: 'solid',
      color: 'blue'
    },
    '&::after': {
      display: 'block'
    },
    '&.modifier': {
      color: 'pink'
    },
    '& $test': {
      background: 'green'
    }
  }
});
`````````````````````````````````````

With JSS 6.0.0 and upper output is:
`````````````````````````````````````css
.test-475557099 {
  background: red;
}
.block-694224615 {
  color: red;
  border: 2px solid blue;
  padding: 10px;
}
..block-694224615::after-3168510914 { // ERROR
  display: block;
}
..block-694224615.modifier-915668220 { // ERROR
  color: pink;
}
..block-694224615 .test-475557099-3096802242 { // ERROR
  background: green;
}
`````````````````````````````````````

And with JSS under 6.0.0 output is:
`````````````````````````````````````css
.test-475557099 {
  background: red;
}
.block-694224615 {
  color: red;
  border: 2px solid blue;
  padding: 10px;
}
.block-694224615::after { // OK
  display: block;
}
.block-694224615.modifier { // OK
  color: pink;
}
.block-694224615 .test-475557099 { // OK
  background: green;
}
`````````````````````````````````````
