### ISSUE TITLE
[jss-expand] background-image

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#385]
Currently if using background: {image: ...}, it compiles to `background: ...image`, this will work with `url()` but won't work with a gradient.

**Comment by kof** [comment]
cc @typical000 wdyt? Shouldn't we always compile to background-image?

**Comment by typical000** [comment]
Yeah, I think we can do it. It will be simple in realization, and we don't loose too much in performance, you can look:
https://github.com/cssinjs/jss-expand/pull/15

But here is one thing - in we do this in such way `background-image` will be everytime separated from original `background` rule
For e.g.:

JS:
```````````````````````````````````js
var sheet = jss.createStyleSheet({
  a: {
    background: {
      image: ['linear-gradient(#fff, #000)', 'linear-gradient(#ff0, #00f)', ]
    }
  },
  b: {
    background: {
      color: '#ff0',
      image: 'url(test.jpg)',
      position: 'center center',
      repeat: 'no-repeat',
      size: [20, 50]
    }
  },
});
```````````````````````````````````
Compiled CSS:
```````````````````````````````````css
.a-3519274874 {
  background-image: linear-gradient(#fff, #000),linear-gradient(#ff0, #00f);
}
.b-4042366338 {
  background: #ff0 center center no-repeat;
  background-size: 20px 50px;
  background-image: url(test.jpg);
}
```````````````````````````````````
