### ISSUE TITLE
Problem using local references inside globals

### ISSUE THREAD

**Issue by JeffreyATW** [cssinjs/jss#596]
Here is some example JSS:

```js
const styles = {
  large: {
    fontSize: 'large',
  },

  '@global tr:not($large)': {
    fontSize: 'small',
  },
};
```

This compiles to:

```css
.large-0-5 {
  font-size: large;
}
tr:not($large) {
  font-size: small;
}
```

But I would expect this to compile to:

```css
.large-0-5 {
  font-size: large;
}
tr:not(.large-0-5) {
  font-size: small;
}
```

Any advice?
