### ISSUE TITLE
[jss-expand] flex array notation

### ISSUE THREAD

**Issue by kof** [cssinjs/jss#633]
Currently we don't handle flex array notation

```js
{
  container: {
    flex: [0, 0, 10]
  }
} 
```

results in

```css
.container-0-22 {
  flex: 0 0 10;
}
```

We should a apply a default value to the last argument, which is flex-basis.

cc @typical000 @ilyador
