### ISSUE TITLE
[jss-nested] Classes can't be defined in a nested scope?

### ISSUE THREAD

**Issue by carlgunderson** [cssinjs/jss#635]
Looking at this example: https://github.com/cssinjs/jss-nested#use-rulename-to-reference-a-local-rule-within-the-same-style-sheet

Why does a class need to be defined at the root level in order to be usable in nesting? Is there a technical JSS reason for needing this structure? In the example, say the only button you have is inside .container, and you don't need/want it to have any styles outside that scope. Obviously just adding something like <code>button: {}</code> at the root fixes the issue. I'm just wondering if I'm missing something, because this is a common usage pattern with CSS preprocessors that support nesting.

**Comment by kof** [comment]
It would be easier to understand if you use examples.

So your question is why do we need:

```js
{
  button: {
    '& span': {color: red}
  }
}
```
instead of 

```js
{
  '& span': {color: red}
}
```

Do I understand correctly?

**Comment by carlgunderson** [comment]
Apologies. Here is an example:

```css
{
  container: {
    '& containerChild': {color: red}
  }
  containerChild: {} // This needs to exist for the above to work
}
```

Why can't we just define `containerChild` where it lives, i.e. inside `container`?
