### ISSUE TITLE
Is there a way to write nested rules?

### ISSUE THREAD

**Issue by gnapse** [cssinjs/jss#654]
The styles in the [playground](https://codesandbox.io/s/z21lpmvv33) could've been easily written in css without the need to declare three class names (using sass here for succinctness but plain old css also supports the notations with more repetition: `.wrapper > h1 { ... }` `.wrapper > a { ... }`):

```css
.wrapper {
  padding: 40;
  background: #f7df1e;
  text-align: center;
  > h1 {
    font-size: 40;
    font-weight: 900;
    color: #24292e;
  }
  > a {
    color: #24292e;
    &:hover {
      opacity: 0.5;
    }
  }
}
```

Instead of declaring a class name for the `<h1>` and the `<a>` elements inside the top-level element, you can reference them as shown above. Can't nested elements be referenced this way, similarly to how you can reference `&:hover`, etc?

Perhaps something like this:

```javascript
const styles = {
  wrapper: {
    padding: 40,
    background: '#f7df1e',
    textAlign: 'center',
    '> h1': {
      font: {
        size: 40,
        weight: 900
      },
      color: '#24292e'
    },
    '> a': {
      color: '#24292e',
      '&:hover': {
        opacity: 0.5
      }
    }
  }
}
```

Or is it necessary to create a class name for each and every single element that one wants to target with some rules?
