### ISSUE TITLE
[jss-nested] nesting like Sass include-media

### ISSUE THREAD

**Issue by trusktr** [cssinjs/jss#838]
__Is your feature request related to a problem? Please describe.__

In Sass we can do

```scss
    html {
        @include media('>=XS4') {
            #root, #header, #mobileMenu {
                transform: scale( $scale-xs4 );
                width: calc( 100% * 1 / #{ $scale-xs4 } );
            }
        }
    }
```

Can we do similar with JSS? I don't see it in the docs.

__Describe the solution you'd like__

To write something like

```js
const style = {
    'html': {
        [`@media (max-width: ${XS4})`]: {
            '& #root, & #header, & #mobileMenu': (`
                transform: scale( ${theme.media.scaleXS5} );
                width: calc( 100% * 1 / ${theme.media.scaleXS5} );
            `),
        },
    }
}
```

so that the nested `&` inside the media query refers to the parent `html` selector that is outside the media query.
