### ISSUE TITLE
font-face fallback order

### ISSUE THREAD

**Issue by 3axap4eHko** [cssinjs/jss#839]
Example:
```js
'@font-face': {
    fontFamily: '"icon-fonts"',
    src: `url(/assets/fonts/icon-fonts.eot)`,
    fallbacks: [
      { src: `url(/assets/fonts/icon-fonts.eot?#iefix) format(embedded-opentype)` },
      { src: `url(/assets/fonts/icon-fonts.ttf) format(truetype)` },
      { src: `url(/assets/fonts/icon-fonts.svg#icon-fonts) format(svg)` },
      { src: `url(/assets/fonts/icon-fonts.woff) format(woff)` },
      { src: `url(/assets/fonts/icon-fonts.woff2) format(woff2)` },
    ],
    fontWeight: 'normal',
    fontStyle: 'normal',
}
```

Expected:
```css
@font-face {
  font-family: "icon-fonts";
  src: url(/assets/fonts/icon-fonts.eot);  
  src: url(/assets/fonts/icon-fonts.eot?#iefix) format(embedded-opentype),
     url(/assets/fonts/icon-fonts.ttf) format(truetype),
     url(/assets/fonts/icon-fonts.svg#icon-fonts) format(svg),
     url(/assets/fonts/icon-fonts.woff) format(woff),
     url(/assets/fonts/icon-fonts.woff2) format(woff2);
  font-weight: normal;
  font-style: normal;
}
```

Received:
```css
@font-face {
  src: url(/assets/fonts/icon-fonts.eot?#iefix) format(embedded-opentype);
  src: url(/assets/fonts/icon-fonts.ttf) format(truetype);
  src: url(/assets/fonts/icon-fonts.svg#icon-fonts) format(svg);
  src: url(/assets/fonts/icon-fonts.woff) format(woff);
  src: url(/assets/fonts/icon-fonts.woff2) format(woff2);
  font-family: "icon-fonts";
  src: url(/assets/fonts/icon-fonts.eot);
  font-weight: normal;
  font-style: normal;
}
```

due to fallback goes first, browser does not load fonts properly

**Comment by kof** [comment]
I think you need to reverse the order of what you consider to be a fallback. CSS will fall back to a previously defined property if the next one fails.

```css
a {
  color: fallback;
  color: unsupported
}
```

So fallback properties should always be defined first.

Second point: you want a src property with multiple values, comma separated. This is also supported: 

``` json
{
  '@font-face': {
      fontFamily: '"icon-fonts"',
      src: `url(/assets/fonts/icon-fonts.eot)`,
      fallbacks: {
        src: [
          `url(/assets/fonts/icon-fonts.eot?#iefix) format(embedded-opentype)`, 
          `url(/assets/fonts/icon-fonts.ttf) format(truetype)`, 
          `url(/assets/fonts/icon-fonts.svg#icon-fonts) format(svg)`,
          `url(/assets/fonts/icon-fonts.woff) format(woff)`,
          `url(/assets/fonts/icon-fonts.woff2) format(woff2)`
          ] 
      },
      fontWeight: 'normal',
      fontStyle: 'normal',
  }

}
```

**Comment by 3axap4eHko** [comment]
In your case fallback renders first and browser doesn't load fonts properly. But once I put `/assets/fonts/icon-fonts.eot` in `fallbacks` and rest of fonts in `src` browser loads `woff2` font.

**Comment by spicydonuts** [comment]
Is this actually resolved/not an issue? On both v9 and v10-alpha.16 supplying fallbacks as shown in the docs produces invalid CSS. I also tried the method shown here and had the same result (one produces a single `src` for fallbacks while the other produces many, but both are invalid as the fallbacks appear before the `font-family` and initial `src`):

```css
@font-face {
  src: url(font-icons.eot?#iefix) format(embedded-opentype), url(font-icons.woff) format(woff), url(font-icons.ttf) format(truetype), url(font-icons.svg#lumi-font-icons) format(svg);
  font-family: font-icons;
  src: url(font-icons.eot);
  font-weight: 400;
  font-style: normal;
}
```

**Comment by 3axap4eHko** [comment]
I just swapped values of src and fallbacks instead of speaking with silence

**Comment by spicydonuts** [comment]
Wouldn't that still be invalid? (assuming you mean swapping the `src` values in my example output) I'm not sure what you mean by "speaking with silence".

**Comment by kof** [comment]
We consider the API works as described, fallbacks in CSS are supposed to be rendered first.

**Comment by spicydonuts** [comment]
I'm still not sure I understand. Are you saying this is the correct way to define these for IE support?

```css
@font-face {
  src: url(font-icons.woff) format(woff);
  font-family: font-icons;
  src: url(font-icons.woff2);
}
```

**Comment by kof** [comment]
the one that you consider to be fallback comes first in css

**Comment by spicydonuts** [comment]
So the main `src` defined in JSS is meant to be the last font in the list and `fallbacks` resembles the common pattern of grouping the available src's but isn't really meant to be the same thing, and the docs just don't reflect this yet?

**Comment by kof** [comment]
Can you point me to the place in the docs that is confusing?

**Comment by spicydonuts** [comment]
The last example in this section on font face: https://cssinjs.org/jss-syntax?v=v10.0.0-alpha.16#font-face

**Comment by kof** [comment]
I am guessing here: the fact that in JSS fallbacks key can be placed in any order, but the fallback properties always land before the actual property is what makes this confusing?

**Comment by spicydonuts** [comment]
Which seems to line up with how font face is usually explained (a src entry for eot and a list of others, but that seems like an arbitrary development unless it was a necessary IE hack at some point): https://www.w3docs.com/learn-css/font-face.html

**Comment by spicydonuts** [comment]
The way you've explained it here makes sense, once I dropped the way I was expecting to see it. I think it's just old conventions floating around in projects and examples combined with that particular example in the docs not matching the actual JSS output.

**Comment by kof** [comment]
How can we make it better or more clear?

**Comment by spicydonuts** [comment]
For the code as-is probably just updating the example output to match the real output (and probably updating both so the `woff2` is last):

```css
@font-face {
  src: url(webfont.eot?#iefix) format(embedded-opentype);
  src: url(webfont.woff2) format(woff2);
  font-family: 'MyWebFont';
  src: url('webfont.eot');
}
```

Another approach could be to remove `fallbacks` entirely and just allow `src` to be an array:

```js
const styles = {
  '@font-face': {
    fontFamily: 'MyWebFont',
    src: [
      'url(webfont.eot)',
      'url(webfont.eot?#iefix) format(embedded-opentype)',
      'url(webfont.woff2) format(woff2)'
    ]
  }
}
```

```css
@font-face {
  font-family: 'MyWebFont';
  src: url('webfont.eot'),
    url(webfont.eot?#iefix) format(embedded-opentype),
    url(webfont.woff2) format(woff2);
}
```

(or an array of `{ src: ... }` to output the same thing as separate `src` properties)
