### ISSUE TITLE
How to use classname in another classname?

### ISSUE THREAD

**Issue by kirill-konshin** [cssinjs/jss#978]
A follow up for https://github.com/cssinjs/react-jss/issues/262.

How to write something like this:

```css
tr.highlighted > td.cell {
  color: red;
}

td.cell {
  color: black;
}
```

Shouldn't it be like for keyframes:

```jsx
const styles = {
  '@keyframes slideRight': {
    from: {opacity: 0},
    to: {opacity: 1}
  },
  container: {
    animationName: '$slideRight'
  },
  tableCell: {
    color: 'black'
  },
  highlightedRow: {
    '& > $tableCell': {
      color: 'red'
    }
  },
}
```
